version: "3.9"
services:
  frontend:
    depends_on:
      - api
    build:
      context: ./projects/frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./projects/frontend:/app

  api:
    depends_on:
      - mongo
    build:
      context: ./projects/api
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./projects/api:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password